### ISSUE TITLE
Modify the speed and contact Redstone

### ISSUE THREAD

**Issue by Koalemon** [theePixelPug/BluestoneMod#1]
How to modify the ticket speed of the repeater to 1 ticket and activate the Redstone as well.(The tick speed of the module doesn't seem practical, I think it's better to modify it to 1 tick)

**Comment by theePixelPug** [comment]
This was an old project of mine just dipping my toes into Minecraft modding. I'm not gonna mess with it anymore, but may revisit the concept at some point. That is, when I finally find the time to. :/

**Comment by Koalemon** [comment]
> This was an old project of mine just dipping my toes into Minecraft modding. I'm not gonna mess with it anymore, but may revisit the concept at some point. That is, when I finally find the time to. :/ 

I would like to know the actual tick for the blue repeater? The introduction states that it is slightly faster than 1 tick. Did you set this? I cannot find the relevant information in the code

**Comment by theePixelPug** [comment]
It wasn't the bluestone repeater, it was the power converter. The repeater-looking block that changes either a redstone or bluestone input and outputs the opposing type of power. Just an fyi though, this mod is very broken. I didn't know how to work with mixins too well, so although it all worked in my modding client, when I booted it in the actual fabric launcher a lot broke.

**Comment by Koalemon** [comment]
> It wasn't the bluestone repeater, it was the power converter. The repeater-looking block that changes either a redstone or bluestone input and outputs the opposing type of power. Just an fyi though, this mod is very broken. I didn't know how to work with mixins too well, so although it all worked in my modding client, when I booted it in the actual fabric launcher a lot broke.

I think this module is very good and belongs to the upgraded version of Instant Redstone mod, but unfortunately it is difficult to maintain.

**Comment by theePixelPug** [comment]
Most of the code is directly taken from the actual Minecraft redstone code. My process was pretty much, copy Minecraft's redstone code, change it to bluestone, then add the bluestone interactions to the world code using mixins.

**Comment by Koalemon** [comment]
> Most of the code is directly taken from the actual Minecraft redstone code. My process was pretty much, copy Minecraft's redstone code, change it to bluestone, then add the bluestone interactions to the world code using mixins.

Strangely, when there are many blue repeaters, the delay becomes 1 tick, which is exactly the same as the original Redstone repeater.(The bluestone repeater has lost its feature of being slightly faster than 1 tick)

**Comment by theePixelPug** [comment]
Like I said earlier, the bluestone repeater is not faster than 1 tick, it's the power converter.

**Comment by Koalemon** [comment]
> Like I said earlier, the bluestone repeater is not faster than 1 tick, it's the power converter.

I have familiarized myself with modules and i am also a beginner in module development. May I ask if you only want to keep the blue repeater and delete all other blocks. Which Java files should I keep.

**Comment by Koalemon** [comment]
> Like I said earlier, the bluestone repeater is not faster than 1 tick, it's the power converter.

Thank you for your previous explanation. I have now completely solved my problem, and this module is also the first one I modified
